'use client';

import { Check, Clock3, FileCheck2, Fingerprint, Menu, ShieldCheck, UserCheck, UserRoundX, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import questionData from '@/data/questions.json';
import { canReviewBank, type AccountStatus, type AppUser, type AuditEntry, type CollaborationState, type MemberProfile, type PlatformRole, type Question, type QuestionProposal } from '@/lib/medguard-types';
import { cn as cx, nowIso } from '@/lib/utils';

type Tab = 'overview' | 'registrations' | 'roles' | 'qbanks' | 'proposals' | 'student-ids' | 'audit';
function formatDate(value?: string) { return value ? new Intl.DateTimeFormat('en', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'; }
function audit(user: AppUser, action: string, entityType: AuditEntry['entityType'], entityId: string, detail: string): AuditEntry { return { id: crypto.randomUUID(), action, entityType, entityId, actorId: user.uid, actorName: user.displayName, createdAt: nowIso(), detail }; }

function DiffField({ label, current, proposed }: { label: string; current: string; proposed: string }) {
  const changed = current !== proposed;
  return <div className="grid gap-2 sm:grid-cols-2"><div className="rounded-xl border bg-muted/25 p-3"><span className="text-[10px] font-bold uppercase text-muted-foreground">Current · {label}</span><p className="mt-2 whitespace-pre-wrap text-xs leading-5">{current || '—'}</p></div><div className={cx('rounded-xl border p-3', changed ? 'border-emerald-300 bg-emerald-50 dark:border-emerald-500/30 dark:bg-emerald-500/10' : 'bg-muted/25')}><span className={cx('text-[10px] font-bold uppercase', changed ? 'text-emerald-700 dark:text-emerald-300' : 'text-muted-foreground')}>Proposed · {label}{changed ? ' · changed' : ''}</span><p className="mt-2 whitespace-pre-wrap text-xs leading-5">{proposed || '—'}</p></div></div>;
}

export function AdminDashboard({ user, collaboration, update }: { user: AppUser; collaboration: CollaborationState; update: (updater: (current: CollaborationState) => CollaborationState) => void }) {
  const canAccess = user.role === 'super_admin' || user.platformRoles.includes('access_manager') || user.role === 'admin' || user.role === 'access_manager';
  const isRoot = user.role === 'super_admin';
  const isReviewer = isRoot || user.platformRoles.includes('reviewer') || user.role === 'reviewer';
  const tabs = useMemo(() => ([['overview', 'Overview'], ...(canAccess ? [['registrations', 'Registrations']] : []), ...(isRoot ? [['student-ids', 'Student IDs'], ['roles', 'Role requests']] : []), ...(isRoot || isReviewer ? [['qbanks', isRoot ? 'All QBanks' : 'QBanks']] : []), ...(isReviewer || collaboration.qbanks.some((bank) => canReviewBank(user, bank, collaboration.memberships)) ? [['proposals', 'Edit review']] : []), ...(isRoot ? [['audit', 'Audit log']] : [])] as Array<[Tab, string]>), [canAccess, collaboration, isReviewer, isRoot, user]);
  const [tab, setTab] = useState<Tab>('overview');
  const [idText, setIdText] = useState('');
  const pendingMembers = collaboration.members.filter((item) => item.status === 'pending');
  const reviewable = collaboration.proposals.filter((proposal) => proposal.status === 'pending' && collaboration.qbanks.some((bank) => bank.id === proposal.qbankId && canReviewBank(user, bank, collaboration.memberships)));
  const roleRequests = collaboration.roleApplications.filter((item) => item.status === 'pending');

  function reviewMember(uid: string, status: AccountStatus) {
    const reviewedAt = nowIso();
    update((current) => ({ ...current, members: current.members.map((item) => item.uid === uid ? { ...item, status, approvedAt: status === 'approved' ? reviewedAt : item.approvedAt, approvedById: user.uid, approvedByName: user.displayName } : item), auditLog: [audit(user, `registration_${status}`, 'account', uid, `${status} membership request.`), ...current.auditLog] }));
  }

  function toggleSuspended(member: MemberProfile) {
    update((current) => ({ ...current, members: current.members.map((item) => item.uid === member.uid ? { ...item, suspended: !item.suspended } : item), auditLog: [audit(user, member.suspended ? 'account_restored' : 'account_blocked', 'account', member.uid, `${member.displayName} access ${member.suspended ? 'restored' : 'blocked'}.`), ...current.auditLog] }));
  }

  function addStudentIds() {
    const values = [...new Set(idText.split(/[\s,;]+/).map((item) => item.trim().toUpperCase()).filter(Boolean))];
    if (!values.length) return;
    const createdAt = nowIso();
    update((current) => { const existing = new Set(current.allowedUniversityIds.map((item) => item.id)); const added = values.filter((id) => !existing.has(id)).map((id) => ({ id, addedAt: createdAt, addedById: user.uid })); return { ...current, allowedUniversityIds: [...added, ...current.allowedUniversityIds], auditLog: added.length ? [audit(user, 'student_ids_added', 'university_id', added[0].id, `${added.length} eligible IDs added.`), ...current.auditLog] : current.auditLog }; });
    setIdText('');
  }

  function reviewRole(applicationId: string, approved: boolean) {
    const application = collaboration.roleApplications.find((item) => item.id === applicationId);
    if (!application || !isRoot) return;
    const reviewedAt = nowIso();
    update((current) => ({
      ...current,
      roleApplications: current.roleApplications.map((item) => item.id === applicationId ? { ...item, status: approved ? 'approved' : 'rejected', reviewedAt, reviewedById: user.uid, reviewedByName: user.displayName } : item),
      members: approved ? current.members.map((member) => member.uid === application.userId ? { ...member, tier: application.requestedRole === 'pro' || application.requestedRole === 'access_manager' ? 'pro' : member.tier, platformRoles: application.requestedRole === 'pro' ? member.platformRoles : [...new Set([...member.platformRoles, application.requestedRole as PlatformRole])] } : member) : current.members,
      auditLog: [audit(user, approved ? 'role_request_approved' : 'role_request_rejected', 'role', application.id, `${application.requestedRole} request by ${application.userName}.`), ...current.auditLog],
    }));
  }

  function reviewProposal(proposal: QuestionProposal, status: 'approved' | 'rejected') {
    const bank = collaboration.qbanks.find((item) => item.id === proposal.qbankId);
    if (!bank || !canReviewBank(user, bank, collaboration.memberships)) return;
    update((current) => {
      let approvedQuestions = current.approvedQuestions;
      if (status === 'approved') {
        const available = [...(questionData as Question[]).map((item) => ({ ...item, qbankId: item.qbankId ?? 'smle-gs' })), ...approvedQuestions];
        const existing = proposal.questionId ? available.find((item) => item.id === proposal.questionId) : undefined;
        const question: Question = { id: proposal.questionId ?? `shared-${crypto.randomUUID()}`, number: existing?.number ?? Math.max(0, ...available.filter((item) => item.qbankId === proposal.qbankId).map((item) => item.number)) + 1, qbankId: proposal.qbankId, specialty: proposal.payload.specialty, topic: proposal.payload.topic, stem: proposal.payload.stem, options: proposal.payload.options, answer: proposal.payload.answer, answerLetter: 'ABCD'[proposal.payload.answer], explanation: proposal.payload.explanation, sourceReference: proposal.payload.sourceReference, sourcePage: existing?.sourcePage ?? 0, sourceFile: existing?.sourceFile ?? proposal.payload.sourceReference, revision: (existing?.revision ?? 0) + 1, isCustom: true };
        approvedQuestions = [...approvedQuestions.filter((item) => item.id !== question.id), question];
      }
      const reviewedAt = nowIso();
      return { ...current, approvedQuestions, proposals: current.proposals.map((item) => item.id === proposal.id ? { ...item, status, reviewedById: user.uid, reviewedByName: user.displayName, reviewedAt } : item), auditLog: [audit(user, `question_proposal_${status}`, 'question', proposal.id, `${proposal.editKinds.join(', ')} by ${proposal.proposedByName}.`), ...current.auditLog] };
    });
  }

  return <><header className="sticky top-0 z-30 border-b bg-card/90 px-4 py-4 backdrop-blur-xl sm:px-7"><div className="mx-auto flex max-w-[1260px] items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><button aria-label="Open navigation" onClick={() => window.dispatchEvent(new Event('medguard-open-menu'))} className="grid size-10 shrink-0 place-items-center rounded-xl border lg:hidden"><Menu className="size-5" /></button><div><div className="flex items-center gap-2"><ShieldCheck className="size-5 text-primary" /><h1 className="font-bold">Administration</h1></div><p className="text-xs text-muted-foreground">Least-privilege access and QBank governance</p></div></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-[10px] font-bold text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300">{isRoot ? 'SUPERADMIN · MFA' : user.platformRoles.join(' · ').toUpperCase()}</span></div></header><div className="mx-auto max-w-[1260px] p-4 sm:p-7"><div className="mb-6 flex gap-2 overflow-x-auto">{tabs.map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={cx('shrink-0 rounded-full border px-4 py-2 text-xs font-bold', tab === id ? 'bg-primary text-primary-foreground' : 'bg-card')}>{label}{id === 'registrations' && pendingMembers.length ? ` · ${pendingMembers.length}` : ''}{id === 'proposals' && reviewable.length ? ` · ${reviewable.length}` : ''}</button>)}</div>
  {tab === 'overview' && <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Pending registrations', pendingMembers.length], ['Role requests', roleRequests.length], ['Visible QBanks', collaboration.qbanks.length], ['Edits to review', reviewable.length]].map(([label, value]) => <article key={label} className="rounded-2xl bg-card p-5 ring-1 ring-border"><p className="text-sm font-semibold text-muted-foreground">{label}</p><strong className="mt-2 block text-3xl">{value}</strong></article>)}</div>}
  {tab === 'registrations' && <section className="overflow-hidden rounded-2xl bg-card ring-1 ring-border"><div className="border-b p-5"><h2 className="font-bold">Registration and access</h2><p className="text-xs text-muted-foreground">Access Managers can approve, reject, block, or restore accounts only.</p></div><div className="divide-y">{collaboration.members.map((member) => <div key={member.uid} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><strong className="text-sm">{member.displayName}</strong><p className="truncate text-xs text-muted-foreground">{member.email} · {member.universityId} · {member.tier}</p></div><span className="text-[10px] font-bold uppercase text-muted-foreground">{member.suspended ? 'blocked' : member.status}</span><div className="flex gap-2">{member.status === 'pending' && <><button onClick={() => reviewMember(member.uid, 'rejected')} className="h-9 rounded-lg border px-3 text-xs font-bold text-red-600"><UserRoundX className="mr-1 inline size-4" />Reject</button><button onClick={() => reviewMember(member.uid, 'approved')} className="h-9 rounded-lg bg-primary px-3 text-xs font-bold text-primary-foreground"><UserCheck className="mr-1 inline size-4" />Approve</button></>}{member.status === 'approved' && member.role !== 'super_admin' && <button onClick={() => toggleSuspended(member)} className="h-9 rounded-lg border px-3 text-xs font-bold">{member.suspended ? 'Restore' : 'Block'}</button>}</div></div>)}</div></section>}
  {tab === 'student-ids' && <div className="grid gap-5 lg:grid-cols-[360px_1fr]"><section className="rounded-2xl bg-card p-5 ring-1 ring-border"><h2 className="flex items-center gap-2 font-bold"><Fingerprint className="size-5 text-primary" />Import eligible IDs</h2><textarea value={idText} onChange={(event) => setIdText(event.target.value)} className="mt-4 min-h-40 w-full rounded-xl border bg-card p-3 font-mono text-sm" placeholder={'442001234\n442001235'} /><button onClick={addStudentIds} className="mt-3 h-10 w-full rounded-xl bg-primary text-xs font-bold text-primary-foreground">Add IDs</button></section><section className="max-h-[620px] overflow-y-auto rounded-2xl bg-card ring-1 ring-border"><div className="divide-y">{collaboration.allowedUniversityIds.map((item) => <div key={item.id} className="flex justify-between p-4 text-sm"><strong className="font-mono">{item.id}</strong><span className="text-xs text-muted-foreground">{item.claimedByName || 'Available'}</span></div>)}</div></section></div>}
  {tab === 'roles' && <section className="overflow-hidden rounded-2xl bg-card ring-1 ring-border"><div className="border-b p-5"><h2 className="font-bold">Role applications</h2><p className="text-xs text-muted-foreground">Only the single Superadmin can approve Pro, Reviewer, or Access Manager privileges.</p></div>{roleRequests.length ? <div className="divide-y">{roleRequests.map((item) => <div key={item.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="flex-1"><strong>{item.userName}</strong><p className="text-xs text-muted-foreground">Requests {item.requestedRole} · {item.reason}</p></div><button onClick={() => reviewRole(item.id, false)} className="h-9 rounded-lg border px-3 text-xs font-bold text-red-600">Reject</button><button onClick={() => reviewRole(item.id, true)} className="h-9 rounded-lg bg-primary px-3 text-xs font-bold text-primary-foreground">Approve</button></div>)}</div> : <div className="p-10 text-center text-sm text-muted-foreground">No pending role applications.</div>}</section>}
  {tab === 'qbanks' && <section className="grid gap-4 md:grid-cols-2">{collaboration.qbanks.map((bank) => <article key={bank.id} className="rounded-2xl bg-card p-5 ring-1 ring-border"><div className="flex justify-between"><span className="rounded-full bg-primary/10 px-2 py-1 text-[10px] font-bold text-primary">{bank.visibility.toUpperCase()}</span>{bank.visibility === 'private' && isRoot && bank.ownerId !== user.uid && <span className="text-[10px] font-bold text-amber-700">READ-ONLY AUDIT</span>}</div><h3 className="mt-3 font-bold">{bank.name}</h3><p className="mt-1 text-sm text-muted-foreground">{bank.description || 'No description.'}</p><p className="mt-4 border-t pt-3 text-xs text-muted-foreground">Owner: {bank.ownerName} · {bank.reviewerIds.length} reviewers · {bank.viewerIds.length} viewers</p></article>)}</section>}
  {tab === 'proposals' && <section className="space-y-4">{reviewable.length ? reviewable.map((proposal) => { const current = proposal.currentSnapshot ?? proposal.payload; return <article key={proposal.id} className="rounded-2xl bg-card p-5 ring-1 ring-border"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-primary/10 px-2 py-1 text-[10px] font-bold text-primary">{proposal.type === 'new_question' ? 'NEW QUESTION' : 'SUGGEST EDIT'}</span>{proposal.editKinds.map((kind) => <span key={kind} className="rounded-full bg-muted px-2 py-1 text-[10px] font-bold">{kind.replaceAll('_', ' ')}</span>)}<span className="ml-auto text-xs text-muted-foreground">{proposal.proposedByName} · {formatDate(proposal.proposedAt)}</span></div><div className="mt-4 space-y-3"><DiffField label="Question" current={current.stem} proposed={proposal.payload.stem} /><DiffField label="Options" current={current.options.map((item, index) => `${'ABCD'[index]}. ${item}`).join('\n')} proposed={proposal.payload.options.map((item, index) => `${'ABCD'[index]}. ${item}`).join('\n')} /><DiffField label="Correct answer" current={'ABCD'[current.answer]} proposed={'ABCD'[proposal.payload.answer]} /><DiffField label="Explanation" current={current.explanation} proposed={proposal.payload.explanation} /><DiffField label="Source" current={current.sourceReference} proposed={proposal.payload.sourceReference} /></div><p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs text-amber-900 dark:bg-amber-500/10 dark:text-amber-200"><strong>Submitter rationale:</strong> {proposal.rationale}</p><div className="mt-4 flex justify-end gap-2"><button onClick={() => reviewProposal(proposal, 'rejected')} className="h-10 rounded-xl border px-4 text-xs font-bold text-red-600"><X className="mr-1 inline size-4" />Reject</button><button onClick={() => reviewProposal(proposal, 'approved')} className="h-10 rounded-xl bg-primary px-4 text-xs font-bold text-primary-foreground"><Check className="mr-1 inline size-4" />Approve changes</button></div></article>; }) : <div className="grid min-h-64 place-items-center rounded-2xl bg-card text-sm text-muted-foreground ring-1 ring-border"><div className="text-center"><FileCheck2 className="mx-auto mb-3 size-8 text-emerald-500" />No authorized edits waiting for review.</div></div>}</section>}
  {tab === 'audit' && <section className="overflow-hidden rounded-2xl bg-card ring-1 ring-border"><div className="border-b p-5"><h2 className="font-bold">Audit log</h2></div><div className="divide-y">{collaboration.auditLog.map((item) => <div key={item.id} className="grid gap-1 p-4 text-sm sm:grid-cols-[170px_160px_1fr_auto]"><strong>{item.actorName}</strong><span className="text-xs font-bold uppercase text-primary">{item.action.replaceAll('_', ' ')}</span><span>{item.detail}</span><time className="text-xs text-muted-foreground">{formatDate(item.createdAt)}</time></div>)}</div></section>}
  </div></>;
}

export function PendingApproval({ user, onSignOut }: { user: AppUser; onSignOut: () => void }) {
  const blocked = user.suspended;
  const rejected = user.status === 'rejected';
  return <main className="grid min-h-screen place-items-center bg-background p-6"><section className="w-full max-w-lg rounded-[26px] bg-card p-8 text-center shadow-xl ring-1 ring-border"><div className="mx-auto grid size-16 place-items-center rounded-2xl bg-amber-50 text-amber-700 dark:bg-amber-500/10 dark:text-amber-300">{blocked || rejected ? <UserRoundX className="size-7" /> : <Clock3 className="size-7" />}</div><p className="mt-6 text-xs font-bold uppercase tracking-widest text-primary">MedGuard membership</p><h1 className="mt-2 text-2xl font-bold">{blocked ? 'Account access blocked' : rejected ? 'Registration not approved' : 'Waiting for approval'}</h1><p className="mx-auto mt-3 text-sm leading-6 text-muted-foreground">{blocked ? 'An Access Manager or the Superadmin must restore this account.' : rejected ? 'Contact your cohort Access Manager if you believe this is a mistake.' : 'Your university ID is reserved until an Access Manager reviews the request.'}</p><button onClick={onSignOut} className="mt-6 h-11 w-full rounded-xl border text-sm font-bold">Sign out</button></section></main>;
}
